### ISSUE TITLE
Vuepress build error: Missing module '../api/latest/index.json'

### ISSUE THREAD

**Issue by thommyho** [oatpp/website#13]
Hi there,
I really like your documentation and wanted to compile it from the git repository.
I ran following commands:
-  npm install (no error)
-  npm run docs:build (error)
It seems to miss following module:
`Error: Cannot find module '../api/latest/index.json'`

Can you please tell me, what I am missing or did wrong?
Thank you very much in advance.

Greetings, Thomas

**Comment by lganzzzo** [comment]
Actually, I better put it here:
[index.json.zip oatpp-1.2.5](https://github.com/oatpp/website/files/7294744/index.json.zip)

**Comment by thommyho** [comment]
Hi @lganzzzo ,
thanks for the fast reply.
`The tool which does that is not yet open-sourced (it needs a good refactoring first)
So you can't generate it on your own yet.`
The `index.json` is good enough for me.
Thank you very much.
Greetings, Thomas
